### ISSUE TITLE
Bootstrapping Error

### ISSUE THREAD

**Issue by kmraok** [asquarezone/ChefZone#16]
Dear Team..I tried bootstrapping on Ubuntu,RH from my workstation.the nodes are adding in hosted chef server successfully. at the end of bootstrapping completioon ,I am getting the below error....could you plz tell me the issue....
Thanks&Regards...
Mallikharjun

PS F:\Mallik's\DevOps\Practics-scripts\chef\chef-repo> knife bootstrap  ec2-13-233-133-179.ap-south-1.compute.amazonaws.
com --sudo -x ubuntu -i  .\chef\cheflab.pem -N ip-172-31-1-129.ap-south-1.compute.internal
Creating new client for ip-172-31-1-129.ap-south-1.compute.internal
Creating new node for ip-172-31-1-129.ap-south-1.compute.internal
Connecting to ec2-13-233-133-179.ap-south-1.compute.amazonaws.com
#<Thread:0x000000000aeb9268@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_con
text.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:
in `block in create_with_logging_context'
        4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_action
s.rb:36:in `block (2 levels) in sessions'
        3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:
in `session'
        2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488
:in `next_session'
        1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:182:
in `new_session'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:194:in `rescue in ne
w_session': Authentication failed for user ubuntu@ec2-13-233-133-179.ap-south-1.compute.amazonaws.com@ec2-13-233-133-179
.ap-south-1.compute.amazonaws.com (Net::SSH::AuthenticationFailed)
Failed to authenticate ubuntu - trying password auth
Enter your password:
#<Thread:0x000000000b280090@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_con
text.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:
in `block in create_with_logging_context'
        4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_action
s.rb:36:in `block (2 levels) in sessions'
        3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:
in `session'
        2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488
:in `next_session'
        1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:182:
in `new_session'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:194:in `rescue in ne
w_session': Authentication failed for user ubuntu@ec2-13-233-133-179.ap-south-1.compute.amazonaws.com@ec2-13-233-133-179
.ap-south-1.compute.amazonaws.com (Net::SSH::AuthenticationFailed)
**ERROR: Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@ec2-13-233-133-179.ap-south-1.compute.amazo**
naws.com@ec2-13-233-133-179.ap-south-1.compute.amazonaws.com
![bootstrap error screens](https://user-images.githubusercontent.com/43443111/49222266-69161680-f401-11e8-861d-37d4bc6b3db4.jpg)
![nodes_in chefserver](https://user-images.githubusercontent.com/43443111/49222349-9e226900-f401-11e8-98c5-e4b7cf9f28a3.jpg)

**Comment by kmraok** [comment]
and after bootstrapping,loged into nodes...and executed command as Sir told.."sudo chef-client"..I am getting empty results...Attaching screens of Ubuntu node & Redhat nodes..
![chef-client_ubuntu error 1](https://user-images.githubusercontent.com/43443111/49223087-b72c1980-f403-11e8-87ec-fe295dd24cd3.jpg)
![chef-client_rh error 1](https://user-images.githubusercontent.com/43443111/49223088-b72c1980-f403-11e8-853d-5fe66684c58e.jpg)

**Comment by kmraok** [comment]
same error
